# cargo-features = ["test-dummy-unstable"]
# cargo-features = ["set_ptr_value"]

[package]
name = "evolve_outer_core"
version = "0.1.0"
edition = "2021"

[dependencies]
# no-std
ahash = { version = "^0.8", default-features = false, optional = true }
hashbrown = { version = "^0.14", default-features = false, optional = true }
indexmap = { version = "^2.5",default-features = false, optional = true }
libc = { version = "^0.2", default-features = false, features = ["const-extern-fn"], optional = true }
libc-print = "^0.1"
regex = { version = "^1.10", default-features = false, optional = true }
evolve_inner_core = { path = "../evolve_inner_core" }

# std
# llvm-sys = { version = "191.0.0-rc1", default-features = false }
# postgres = { version = "0.19.8", default-features = false }

[dev-dependencies]
ctor = {  version = "^0.2", default-features = false }
pretty_assertions = "^1.4"
test-case = "^3.3"

[features]
default = ["string", "stringmap", "regex", "libc_alloc"]
libgc_alloc = []
libc_alloc = ["dep:libc"]
regex = ["dep:regex"]
string = []
stringmap = ["dep:indexmap", "dep:ahash", "dep:hashbrown"]
