[package]
name = "evolve-core"
version = "1.0.0"
edition = "2024"
rust-version = "1.86"
resolver = "3"

[workspace]
members = [
    "evolve_inner_core",
    "evolve_outer_core",
]
#    "inject_global_allocator",

[profile.release]
lto = "fat"
panic = "abort"
