# cargo-features = ["test-dummy-unstable"]
# cargo-features = ["set_ptr_value"]

[package]
name = "evolve-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"

[dependencies]
# no-std
indexmap = { version = "2.5.0",default-features = false }
gmp-mpfr-sys = { version = "1.6.4", default-features = false, features = ["mpfr"] }
regex = { version = "1.10.6", default-features = false }
ahash = { version = "0.8.11", default-features = false }

# std
# llvm-sys = { version = "191.0.0-rc1", default-features = false }
# postgres = { version = "0.19.8", default-features = false }

# sub-dependencies
# sub of gmp-mpfr-sys
libc = { version = "^0.2", default-features = false, features = ["const-extern-fn"] }

[dev-dependencies]
test-case = "3.3.1"
pretty_assertions = "1.4.0"