[package]
name = "evolve_inner_core"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = { version = "^4.6",  default-features = false }

[dev-dependencies]
pretty_assertions = "^1.4"
test-case = "^3.3"
