[package]
name = "evolve_inner_core"
version = "1.0.0"
edition = "2024"

[dependencies]
ordered-float = { version = "5.0",  default-features = false }
num-traits = { version = "0.2",  default-features = false }

[dev-dependencies]
pretty_assertions = "1.4"
test-case = "3.3"
